name: Type check and Lint
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".env.example"
      - ".gitignore"
      - ".husky/**"
      - "biome.json"
      - "commitlint.config.ts"
      - "LICENSE"
      - "README.md"

jobs:
  tsc_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Download deps
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm run typecheck

      - name: Lint
        run: pnpm run lint
